{
  "language": "python",
  "os": [
    "windows"
  ],
  "python": [
    "2.7",
    "3.4",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "3.9-dev",
    "nightly"
  ],
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "python -m unittest Assignments.voltage.test_voltage_data_full.py"
  ]
}